ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['python', '/work2/07965/clans/ls6/Spring_RASR/rasr/scripts/rasr_pipeline_test.py']' command failed.  (See above for error)
Traceback (most recent call last):
  File "/work2/07965/clans/ls6/Spring_RASR/rasr/scripts/rasr_pipeline_test.py", line 40, in <module>
    shutil.copy(file, today.strftime("%m:%d:%Y") + "/vis/")
  File "/work2/07965/clans/miniconda3/envs/rasr/lib/python3.8/shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/work2/07965/clans/miniconda3/envs/rasr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
IsADirectoryError: [Errno 21] Is a directory: '05:06:2022/vis/'

